sever:
  port:8081
spring:
  application:
    name: scorpio_privoder
  cloud:
    nacos:
      discover:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/db_cloudoffer?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource